CREATE TABLE IF NOT EXISTS 'users' (
    'id' INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    'username' TEXT NOT NULL,
    'email' TEXT NULL,
    'hash' TEXT NOT NULL,
    'birthday' DATETIME NOT NULL,
    'registered' DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS 'records' (
    'id' INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, 
    'user_id' INTEGER NOT NULL,
    'name' TEXT NOT NULL,
    'timestamp' DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id)
);

INSERT INTO records ('user_id', 'name')
    VALUES (1, 'I think ');